### ISSUE TITLE
lower option not supported?

### ISSUE THREAD

**Issue by nevace** [lucasconstantino/angular-slug#1]
Hi,

Thanks for the angular wrapper. I've noticed that the lowercase option isn't supported. {lower: true} Do you plan on adding this in?

**Comment by nevace** [comment]
My mistake, the slug library dependency just needs updating to the latest. If you could update this, it would be appreciated, thanks.

**Comment by lucasconstantino** [comment]
Do you mind working on a pull-request? Even though this is very simple I'm currently with no time at all to test changes to it.

**Comment by nevace** [comment]
Yeah that's fine, I already forked it because I needed it asap but will remove mine when yours is updated. Shall I change the version number to 0.0.4 and you tag it in git or do I tag it so you can just merge?

**Comment by lucasconstantino** [comment]
Please, tag it ;)
